/* This file was generated by upbc (the upb compiler) from the input
 * file:
 *
 *     src/proto/grpc/gcp/common.proto
 *
 * Do not edit -- your changes will be discarded when the file is
 * regenerated. */

#ifndef SRC_PROTO_GRPC_GCP_COMMON_PROTO_UPB_H_
#define SRC_PROTO_GRPC_GCP_COMMON_PROTO_UPB_H_

#include "upb/generated_util.h"
#include "upb/msg.h"
#include "upb/decode.h"
#include "upb/encode.h"

#include "upb/port_def.inc"

#ifdef __cplusplus
extern "C" {
#endif

struct s2a_proto_Identity;
struct s2a_proto_Identity_AttributesEntry;
typedef struct s2a_proto_Identity s2a_proto_Identity;
typedef struct s2a_proto_Identity_AttributesEntry s2a_proto_Identity_AttributesEntry;
extern const upb_msglayout s2a_proto_Identity_msginit;
extern const upb_msglayout s2a_proto_Identity_AttributesEntry_msginit;

typedef enum {
  s2a_proto_AES_128_GCM_SHA256 = 0,
  s2a_proto_AES_256_GCM_SHA384 = 1,
  s2a_proto_CHACHA20_POLY1305_SHA256 = 2
} s2a_proto_Ciphersuite;

typedef enum {
  s2a_proto_TLS1_2 = 0,
  s2a_proto_TLS1_3 = 1
} s2a_proto_TLSVersion;


/* s2a.proto.Identity */

UPB_INLINE s2a_proto_Identity *s2a_proto_Identity_new(upb_arena *arena) {
  return (s2a_proto_Identity *)upb_msg_new(&s2a_proto_Identity_msginit, arena);
}
UPB_INLINE s2a_proto_Identity *s2a_proto_Identity_parse(const char *buf, size_t size,
                        upb_arena *arena) {
  s2a_proto_Identity *ret = s2a_proto_Identity_new(arena);
  return (ret && upb_decode(buf, size, ret, &s2a_proto_Identity_msginit, arena)) ? ret : NULL;
}
UPB_INLINE char *s2a_proto_Identity_serialize(const s2a_proto_Identity *msg, upb_arena *arena, size_t *len) {
  return upb_encode(msg, &s2a_proto_Identity_msginit, arena, len);
}

typedef enum {
  s2a_proto_Identity_identity_oneof_spiffe_id = 1,
  s2a_proto_Identity_identity_oneof_hostname = 2,
  s2a_proto_Identity_identity_oneof_NOT_SET = 0
} s2a_proto_Identity_identity_oneof_oneofcases;
UPB_INLINE s2a_proto_Identity_identity_oneof_oneofcases s2a_proto_Identity_identity_oneof_case(const s2a_proto_Identity* msg) { return (s2a_proto_Identity_identity_oneof_oneofcases)UPB_FIELD_AT(msg, int32_t, UPB_SIZE(12, 24)); }

UPB_INLINE bool s2a_proto_Identity_has_spiffe_id(const s2a_proto_Identity *msg) { return _upb_has_oneof_field(msg, UPB_SIZE(12, 24), 1); }
UPB_INLINE upb_strview s2a_proto_Identity_spiffe_id(const s2a_proto_Identity *msg) { return UPB_READ_ONEOF(msg, upb_strview, UPB_SIZE(4, 8), UPB_SIZE(12, 24), 1, upb_strview_make("", strlen(""))); }
UPB_INLINE bool s2a_proto_Identity_has_hostname(const s2a_proto_Identity *msg) { return _upb_has_oneof_field(msg, UPB_SIZE(12, 24), 2); }
UPB_INLINE upb_strview s2a_proto_Identity_hostname(const s2a_proto_Identity *msg) { return UPB_READ_ONEOF(msg, upb_strview, UPB_SIZE(4, 8), UPB_SIZE(12, 24), 2, upb_strview_make("", strlen(""))); }
UPB_INLINE const s2a_proto_Identity_AttributesEntry* const* s2a_proto_Identity_attributes(const s2a_proto_Identity *msg, size_t *len) { return (const s2a_proto_Identity_AttributesEntry* const*)_upb_array_accessor(msg, UPB_SIZE(0, 0), len); }

UPB_INLINE void s2a_proto_Identity_set_spiffe_id(s2a_proto_Identity *msg, upb_strview value) {
  UPB_WRITE_ONEOF(msg, upb_strview, UPB_SIZE(4, 8), value, UPB_SIZE(12, 24), 1);
}
UPB_INLINE void s2a_proto_Identity_set_hostname(s2a_proto_Identity *msg, upb_strview value) {
  UPB_WRITE_ONEOF(msg, upb_strview, UPB_SIZE(4, 8), value, UPB_SIZE(12, 24), 2);
}
UPB_INLINE s2a_proto_Identity_AttributesEntry** s2a_proto_Identity_mutable_attributes(s2a_proto_Identity *msg, size_t *len) {
  return (s2a_proto_Identity_AttributesEntry**)_upb_array_mutable_accessor(msg, UPB_SIZE(0, 0), len);
}
UPB_INLINE s2a_proto_Identity_AttributesEntry** s2a_proto_Identity_resize_attributes(s2a_proto_Identity *msg, size_t len, upb_arena *arena) {
  return (s2a_proto_Identity_AttributesEntry**)_upb_array_resize_accessor(msg, UPB_SIZE(0, 0), len, UPB_SIZE(4, 8), UPB_TYPE_MESSAGE, arena);
}
UPB_INLINE struct s2a_proto_Identity_AttributesEntry* s2a_proto_Identity_add_attributes(s2a_proto_Identity *msg, upb_arena *arena) {
  struct s2a_proto_Identity_AttributesEntry* sub = (struct s2a_proto_Identity_AttributesEntry*)upb_msg_new(&s2a_proto_Identity_AttributesEntry_msginit, arena);
  bool ok = _upb_array_append_accessor(
      msg, UPB_SIZE(0, 0), UPB_SIZE(4, 8), UPB_TYPE_MESSAGE, &sub, arena);
  if (!ok) return NULL;
  return sub;
}

/* s2a.proto.Identity.AttributesEntry */

UPB_INLINE s2a_proto_Identity_AttributesEntry *s2a_proto_Identity_AttributesEntry_new(upb_arena *arena) {
  return (s2a_proto_Identity_AttributesEntry *)upb_msg_new(&s2a_proto_Identity_AttributesEntry_msginit, arena);
}
UPB_INLINE s2a_proto_Identity_AttributesEntry *s2a_proto_Identity_AttributesEntry_parse(const char *buf, size_t size,
                        upb_arena *arena) {
  s2a_proto_Identity_AttributesEntry *ret = s2a_proto_Identity_AttributesEntry_new(arena);
  return (ret && upb_decode(buf, size, ret, &s2a_proto_Identity_AttributesEntry_msginit, arena)) ? ret : NULL;
}
UPB_INLINE char *s2a_proto_Identity_AttributesEntry_serialize(const s2a_proto_Identity_AttributesEntry *msg, upb_arena *arena, size_t *len) {
  return upb_encode(msg, &s2a_proto_Identity_AttributesEntry_msginit, arena, len);
}

UPB_INLINE upb_strview s2a_proto_Identity_AttributesEntry_key(const s2a_proto_Identity_AttributesEntry *msg) { return UPB_FIELD_AT(msg, upb_strview, UPB_SIZE(0, 0)); }
UPB_INLINE upb_strview s2a_proto_Identity_AttributesEntry_value(const s2a_proto_Identity_AttributesEntry *msg) { return UPB_FIELD_AT(msg, upb_strview, UPB_SIZE(8, 16)); }

UPB_INLINE void s2a_proto_Identity_AttributesEntry_set_key(s2a_proto_Identity_AttributesEntry *msg, upb_strview value) {
  UPB_FIELD_AT(msg, upb_strview, UPB_SIZE(0, 0)) = value;
}
UPB_INLINE void s2a_proto_Identity_AttributesEntry_set_value(s2a_proto_Identity_AttributesEntry *msg, upb_strview value) {
  UPB_FIELD_AT(msg, upb_strview, UPB_SIZE(8, 16)) = value;
}

#ifdef __cplusplus
}  /* extern "C" */
#endif

#include "upb/port_undef.inc"

#endif  /* SRC_PROTO_GRPC_GCP_COMMON_PROTO_UPB_H_ */
