/* This file was generated by upbc (the upb compiler) from the input
 * file:
 *
 *     src/proto/grpc/gcp/s2a.proto
 *
 * Do not edit -- your changes will be discarded when the file is
 * regenerated. */

#include <stddef.h>
#include "upb/msg.h"
#include "src/proto/grpc/gcp/s2a.upb.h"

#include "upb/port_def.inc"

static const upb_msglayout *const s2a_Identity_submsgs[1] = {
  &s2a_Identity_AttributesEntry_msginit,
};

static const upb_msglayout_field s2a_Identity__fields[3] = {
  {1, UPB_SIZE(4, 8), UPB_SIZE(-13, -25), 0, 9, 1},
  {2, UPB_SIZE(4, 8), UPB_SIZE(-13, -25), 0, 9, 1},
  {3, UPB_SIZE(0, 0), 0, 0, 11, 3},
};

const upb_msglayout s2a_Identity_msginit = {
  &s2a_Identity_submsgs[0],
  &s2a_Identity__fields[0],
  UPB_SIZE(16, 32), 3, false,
};

static const upb_msglayout_field s2a_Identity_AttributesEntry__fields[2] = {
  {1, UPB_SIZE(0, 0), 0, 0, 9, 1},
  {2, UPB_SIZE(8, 16), 0, 0, 9, 1},
};

const upb_msglayout s2a_Identity_AttributesEntry_msginit = {
  NULL,
  &s2a_Identity_AttributesEntry__fields[0],
  UPB_SIZE(16, 32), 2, false,
};

static const upb_msglayout *const s2a_ClientSessionStartReq_submsgs[2] = {
  &s2a_Identity_msginit,
};

static const upb_msglayout_field s2a_ClientSessionStartReq__fields[7] = {
  {1, UPB_SIZE(28, 40), 0, 0, 9, 3},
  {2, UPB_SIZE(0, 0), 0, 0, 14, 1},
  {3, UPB_SIZE(8, 8), 0, 0, 14, 1},
  {4, UPB_SIZE(32, 48), 0, 0, 14, 3},
  {5, UPB_SIZE(36, 56), 0, 0, 11, 3},
  {6, UPB_SIZE(24, 32), 0, 0, 11, 1},
  {7, UPB_SIZE(16, 16), 0, 0, 9, 1},
};

const upb_msglayout s2a_ClientSessionStartReq_msginit = {
  &s2a_ClientSessionStartReq_submsgs[0],
  &s2a_ClientSessionStartReq__fields[0],
  UPB_SIZE(40, 64), 7, false,
};

static const upb_msglayout *const s2a_ServerSessionStartReq_submsgs[1] = {
  &s2a_Identity_msginit,
};

static const upb_msglayout_field s2a_ServerSessionStartReq__fields[6] = {
  {1, UPB_SIZE(24, 32), 0, 0, 9, 3},
  {2, UPB_SIZE(0, 0), 0, 0, 14, 1},
  {3, UPB_SIZE(8, 8), 0, 0, 14, 1},
  {4, UPB_SIZE(28, 40), 0, 0, 14, 3},
  {5, UPB_SIZE(32, 48), 0, 0, 11, 3},
  {6, UPB_SIZE(16, 16), 0, 0, 12, 1},
};

const upb_msglayout s2a_ServerSessionStartReq_msginit = {
  &s2a_ServerSessionStartReq_submsgs[0],
  &s2a_ServerSessionStartReq__fields[0],
  UPB_SIZE(40, 64), 6, false,
};

static const upb_msglayout_field s2a_SessionNextReq__fields[1] = {
  {1, UPB_SIZE(0, 0), 0, 0, 12, 1},
};

const upb_msglayout s2a_SessionNextReq_msginit = {
  NULL,
  &s2a_SessionNextReq__fields[0],
  UPB_SIZE(8, 16), 1, false,
};

static const upb_msglayout_field s2a_ResumptionTicketReq__fields[1] = {
  {1, UPB_SIZE(0, 0), 0, 0, 12, 1},
};

const upb_msglayout s2a_ResumptionTicketReq_msginit = {
  NULL,
  &s2a_ResumptionTicketReq__fields[0],
  UPB_SIZE(8, 16), 1, false,
};

static const upb_msglayout *const s2a_SessionReq_submsgs[4] = {
  &s2a_ClientSessionStartReq_msginit,
  &s2a_ResumptionTicketReq_msginit,
  &s2a_ServerSessionStartReq_msginit,
  &s2a_SessionNextReq_msginit,
};

static const upb_msglayout_field s2a_SessionReq__fields[4] = {
  {1, UPB_SIZE(0, 0), UPB_SIZE(-5, -9), 0, 11, 1},
  {2, UPB_SIZE(0, 0), UPB_SIZE(-5, -9), 2, 11, 1},
  {3, UPB_SIZE(0, 0), UPB_SIZE(-5, -9), 3, 11, 1},
  {4, UPB_SIZE(0, 0), UPB_SIZE(-5, -9), 1, 11, 1},
};

const upb_msglayout s2a_SessionReq_msginit = {
  &s2a_SessionReq_submsgs[0],
  &s2a_SessionReq__fields[0],
  UPB_SIZE(8, 16), 4, false,
};

static const upb_msglayout_field s2a_SessionState__fields[10] = {
  {1, UPB_SIZE(0, 0), 0, 0, 14, 1},
  {2, UPB_SIZE(8, 8), 0, 0, 14, 1},
  {3, UPB_SIZE(16, 16), 0, 0, 4, 1},
  {4, UPB_SIZE(24, 24), 0, 0, 4, 1},
  {5, UPB_SIZE(32, 32), 0, 0, 12, 1},
  {6, UPB_SIZE(40, 48), 0, 0, 12, 1},
  {7, UPB_SIZE(48, 64), 0, 0, 12, 1},
  {8, UPB_SIZE(56, 80), 0, 0, 12, 1},
  {9, UPB_SIZE(64, 96), 0, 0, 12, 1},
  {10, UPB_SIZE(72, 112), 0, 0, 12, 1},
};

const upb_msglayout s2a_SessionState_msginit = {
  NULL,
  &s2a_SessionState__fields[0],
  UPB_SIZE(80, 128), 10, false,
};

static const upb_msglayout *const s2a_SessionResult_submsgs[3] = {
  &s2a_Identity_msginit,
  &s2a_SessionState_msginit,
};

static const upb_msglayout_field s2a_SessionResult__fields[4] = {
  {1, UPB_SIZE(0, 0), 0, 0, 9, 1},
  {2, UPB_SIZE(8, 16), 0, 1, 11, 1},
  {4, UPB_SIZE(12, 24), 0, 0, 11, 1},
  {5, UPB_SIZE(16, 32), 0, 0, 11, 1},
};

const upb_msglayout s2a_SessionResult_msginit = {
  &s2a_SessionResult_submsgs[0],
  &s2a_SessionResult__fields[0],
  UPB_SIZE(24, 48), 4, false,
};

static const upb_msglayout_field s2a_SessionStatus__fields[2] = {
  {1, UPB_SIZE(0, 0), 0, 0, 13, 1},
  {2, UPB_SIZE(4, 8), 0, 0, 9, 1},
};

const upb_msglayout s2a_SessionStatus_msginit = {
  NULL,
  &s2a_SessionStatus__fields[0],
  UPB_SIZE(16, 32), 2, false,
};

static const upb_msglayout *const s2a_SessionResp_submsgs[2] = {
  &s2a_SessionResult_msginit,
  &s2a_SessionStatus_msginit,
};

static const upb_msglayout_field s2a_SessionResp__fields[4] = {
  {1, UPB_SIZE(4, 8), 0, 0, 12, 1},
  {2, UPB_SIZE(0, 0), 0, 0, 13, 1},
  {3, UPB_SIZE(12, 24), 0, 0, 11, 1},
  {4, UPB_SIZE(16, 32), 0, 1, 11, 1},
};

const upb_msglayout s2a_SessionResp_msginit = {
  &s2a_SessionResp_submsgs[0],
  &s2a_SessionResp__fields[0],
  UPB_SIZE(24, 48), 4, false,
};

#include "upb/port_undef.inc"

